services:
  react-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ..:/app:cached
      - node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      NODE_OPTIONS: "--max-old-space-size=2048"

volumes:
  node_modules: